name: pytorch
channels:
  - defaults
dependencies:
  - _pytorch_select=0.1=cpu_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py37h2bbff1b_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - ca-certificates=2022.2.1=haa95532_0
  - certifi=2021.10.8=py37haa95532_2
  - cffi=1.15.0=py37h2bbff1b_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - debugpy=1.5.1=py37hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - icu=58.2=ha925a31_3
  - importlib_metadata=4.8.2=hd3eb1b0_0
  - intel-openmp=2019.4=245
  - ipython=7.31.1=py37haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.18.1=py37haa95532_1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - jpeg=9d=h2bbff1b_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=7.1.2=pyhd3eb1b0_0
  - jupyter_console=6.4.3=pyhd3eb1b0_0
  - jupyter_core=4.9.2=py37haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - libmklml=2019.0.5=haa95532_0
  - libpng=1.6.37=h2a8f88b_0
  - markupsafe=2.0.1=py37h2bbff1b_0
  - mistune=0.8.4=py37hfa6e2cd_1001
  - mkl=2019.4=245
  - mkl-service=2.3.0=py37h196d8e1_0
  - mkl_fft=1.3.0=py37h46781fe_0
  - mkl_random=1.1.0=py37h675688f_0
  - nbclient=0.5.11=pyhd3eb1b0_0
  - nbconvert=6.1.0=py37haa95532_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ninja=1.10.2=py37h559b2a2_3
  - notebook=6.4.8=py37haa95532_0
  - numpy=1.19.2=py37hadc3359_0
  - numpy-base=1.19.2=py37ha3acd2a_0
  - openssl=1.1.1m=h2bbff1b_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.2.4=py37haa95532_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyqt=5.9.2=py37hd77b12b_6
  - python=3.7.11=h6244533_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pywinpty=2.0.2=py37h5da7b33_0
  - pyzmq=22.3.0=py37hd77b12b_2
  - qt=5.9.7=vc14h73c81de_0
  - qtconsole=5.2.2=pyhd3eb1b0_0
  - qtpy=1.11.2=pyhd3eb1b0_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=58.0.4=py37haa95532_0
  - sip=4.19.13=py37hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.37.0=h2bbff1b_0
  - terminado=0.13.1=py37haa95532_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tornado=6.1=py37h2bbff1b_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py37_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py37haa95532_0
  - wincertstore=0.2=py37haa95532_2
  - winpty=0.4.3=4
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.11=h8cc25b3_4
  - pip:
    - beautifulsoup4==4.10.0
    - bs4==0.0.1
    - charset-normalizer==2.0.10
    - click==8.0.3
    - configparser==5.2.0
    - crypto==1.4.1
    - cycler==0.11.0
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - entrypoints==0.3
    - et-xmlfile==1.1.0
    - flask==2.0.2
    - flask-cors==3.0.10
    - fonttools==4.28.5
    - fsspec==2022.1.0
    - future==0.18.2
    - gitdb==4.0.9
    - gitpython==3.1.26
    - gmpy2==2.1.2
    - greenlet==1.1.2
    - idna==3.3
    - importlib-metadata==4.10.0
    - importlib-resources==5.4.0
    - ipykernel==6.7.0
    - itsdangerous==2.0.1
    - joblib==1.1.0
    - jsonmerge==1.8.0
    - jsonschema==4.4.0
    - jupyter-core==4.9.1
    - kiwisolver==1.3.2
    - lxml==4.8.0
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - naked==0.1.31
    - nest-asyncio==1.5.4
    - nltk==3.7
    - opencv-python==4.5.5.62
    - openpyxl==3.0.9
    - pandas==1.3.5
    - pathtools==0.1.2
    - pillow==9.0.0
    - pipreqs==0.4.11
    - prettytable==3.0.0
    - promise==2.3
    - prompt-toolkit==3.0.24
    - protobuf==3.19.3
    - psutil==5.9.0
    - ptflops==0.6.8
    - pyecharts==1.9.1
    - pymysql==1.0.2
    - pyparsing==3.0.6
    - pyrsistent==0.18.1
    - pytz==2021.3
    - pywin32==303
    - pyyaml==6.0
    - regex==2022.3.2
    - requests==2.27.1
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - sentry-sdk==1.5.2
    - shellescape==3.8.1
    - shortuuid==1.0.8
    - simplejson==3.17.6
    - sklearn==0.0
    - smmap==5.0.0
    - soupsieve==2.3.1
    - sqlalchemy==1.4.31
    - subprocess32==3.5.4
    - termcolor==1.1.0
    - thop==0.0.31-2005241907
    - threadpoolctl==3.0.0
    - torch==1.10.1
    - torchvision==0.11.2
    - tqdm==4.63.0
    - typing-extensions==4.0.1
    - urllib3==1.25.11
    - wandb==0.12.9
    - werkzeug==2.0.2
    - yarg==0.1.9
    - yaspin==2.1.0
prefix: D:\miniconda\envs\pytorch
